# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

 pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo hello from Windows
