trigger:
- main

resources:
- repo: self

pool:
  vmImage: 'windows-latest'

variables:
  imageName: 'msaner/hearc' # This is your specific image name.
  version: '1.0.0' # Example version. Adjust as necessary.
  buildId: '$(Build.BuildId)' # Using Azure DevOps predefined variable for build ID.
  tag: '${{ variables.version }}-build-${{ variables.buildId }}' # Concatenating version and build ID.

steps:
- script: docker build -t $(imageName):$(tag) -f Dockerfile .
  displayName: 'Build Docker image'

- script: docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)
  displayName: 'Login to Docker Hub'

- script: docker push $(imageName):$(tag)
  displayName: 'Push Docker image to Docker Hub'
