# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: Windows
pool:
    vmImage: 'windows-latest'
steps:
  - script: echo hello from Windows
